name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .github/workflows/*
      - '**/README.md'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch latest release version
        id: fetch-latest-release
        uses: reloc8/action-latest-release-version@1.0.0

      - name: Get updated version
        id: updated-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'plugin.json'
          prop_path: 'Version'

      - name: Determine if publish release required
        id: publish-release
        run: |
          $release_ver="${{ steps.fetch-latest-release.outputs.latest-release }}".replace('v','')
          if (${{steps.updated-version.outputs.prop}} -ne $release_ver -and "${{github.ref_name}}" -eq 'master') {
            echo "::set-output name=required::true"
          }

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: |
          dotnet publish 'Wox.Plugin.GoogleSearch.csproj' --framework net5.0-windows  -c Release -o "Wox.Plugin.GoogleSearch"
          7z a -tzip "Wox.Plugin.GoogleSearch.zip" "./Wox.Plugin.GoogleSearch/*"
          rm -r "Wox.Plugin.GoogleSearch"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Wox.Plugin.GoogleSearch.zip
          path: .

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: steps.publish-release.outputs.required == 'true'
        with:
          files: "Wox.Plugin.GoogleSearch.zip"
          tag_name: "v${{steps.updated-version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
