name: Publish Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    paths-ignore:
      - .github/workflows/*
      - '**/README.md'

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}}
      - name: Build
        run: |
          dotnet publish 'Wox.Plugin.GoogleSearch.csproj' --framework net6.0-windows  -c Release -o "Wox.Plugin.GoogleSearch"
          7z a -tzip "Wox.Plugin.GoogleSearch.zip" "./Wox.Plugin.GoogleSearch/*"
          rm -r "Wox.Plugin.GoogleSearch"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Wox.Plugin.GoogleSearch.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}